export const wmoTable = {
  0: "Cloud development not observed or not observable",
  1: "Clouds generally dissolving or becoming less developed",
  2: "State of sky on the whole unchanged",
  3: "Clouds generally forming or developing",
  4: "Visibility reduced by smoke, e.g. veldt or forest fires, industrial smoke or volcanic ashes",
  5: "Haze",
  6: "Widespread dust in suspension in the air, not raised by wind at or near the station at the time of observation",
  7: "Dust or sand raised by wind at or near the station at the time of observation, but no well developed dust whirls or sand whirls, and no duststorm or sandstorm seen",
  8: "Well developed dust whirl or sand whirl seen at or near the station during the preceding hour or at the time ot observation, but no duststorm or sandstorm",
  9: "Duststorm or sandstorm within sight at the time of observation, or at the station during the preceding hour",
  10: "Mist",
  11: "Patches of shallow fog or ice fog",
  12: "More or less continuous of shallow fog or ice fog",
  13: "Lightning visible, no thunder heard",
  14: "Precipitation within sight, not reaching the ground or the surface of the sea",
  15: "Precipitation within sight, reaching the ground or the surface of the sea, but distant",
  16: "Precipitation within sight, reaching the ground or the surface of the sea, near to, but not at the station",
  17: "Thunderstorm, but no precipitation at the time of observation",
  18: "Squalls within sight of station",
  19: "Funnel cloud within sight of station",
  20: "Drizzle(not falling as shower)",
  21: "Rain(not falling as shower)",
  22: "Snow(not falling as shower)",
  23: "Drizzle(not falling as shower)",
  24: "Rain and snow or ice pellets(not falling as shower)",
  25: "Showers of rain",
  26: "Showers of snow, or of rain and snow",
  27: "Showers of hail, or of rain and hail",
  28: "Fog or ice fog",
  29: "Thunderstorm ",
  30: "Slight or moderate duststorm or sandstorm",
  31: "Slight or moderate duststorm or sandstorm",
  32: "Slight or moderate duststorm or sandstorm",
  33: "Severe duststorm or sandstorm",
  34: "Severe duststorm or sandstorm",
  35: "Severe duststorm or sandstorm",
  36: "Slight or moderate blowing snow(below eye level)",
  37: "Heavy drifting snow(below eye level)",
  38: "Slight or moderate blowing snow(above eye level)",
  39: "Heavy drifting snow(above eye level)",
  40: "Fog or ice fog at a distance at the time of observation",
  41: "Fog or ice fog in patches",
  42: "Fog or ice fog, sky visible",
  43: "Fog or ice fog, sky invisible",
  44: "Fog or ice fog, sky visible",
  45: "Fog or ice fog, sky invisible",
  46: "Fog or ice fog, sky visible",
  47: "Fog or ice fog, sky invisible",
  48: "Fog, depositing rime, sky visible",
  49: "Fog, depositing rime, sky invisible",
  50: "Slight intermittent drizzle, not freezing",
  51: "Slight continuous drizzle, not freezing",
  52: "Moderate intermittent drizzle, not freezing",
  53: "Moderate continuous drizzle, not freezing",
  54: "Heavy intermittent drizzle, not freezing",
  55: "Heavy continuous drizzle, not freezing",
  56: "Slight drizzle, freezing",
  57: "Moderate or heavy drizzle, freezing",
  58: "Slight drizzle and rain",
  59: "Moderate or heavy drizzle and rain",
  60: "Slight intermittent rain, not freezing",
  61: "Slight continuous rain, not freezing",
  62: "Moderate intermittent rain, not freezing",
  63: "Moderate continuous rain, not freezing",
  64: "Heavy intermittent rain, not freezing",
  65: "Heavy continuous rain, not freezing",
  66: "Slight rain with freezing",
  67: "Heavy rain with freezing",
  68: "Slight rain with snow",
  69: "Heavy rain with snow",
  70: "Slight intermittent fall of snowflakes",
  71: "Slight continuous fall of snowflakes",
  72: "Moderate intermittent fall of snowflakes",
  73: "Moderate continuous fall of snowflakes",
  74: "Heavy intermittent fall of snowflakes",
  75: "Heavy continuous fall of snowflakes",
  76: "Diamond dust",
  77: "Snow grains",
  78: "Isolated star-like snow crystals",
  79: "Ice pellets",
  80: "Slight rain showers",
  81: "Moderate or heavy rain showers",
  82: "Violent rain showers",
  83: "Slight rain showers and snow mixed",
  84: "Moderate or heavy rain showers and snow mixed",
  85: "Slight snow showers",
  86: "Moderate or heavy snow showers",
  87: "Slight hailing",
  88: "Moderate or heavy hailing",
  89: "Slight hailing",
  90: "Moderate or heavy hailing",
  91: "Slight rain at time of observation",
  92: "Moderate or heavy rain at time of observation",
  93: "Slight snow, or rain and snow mixed or hail",
  94: "Moderate or heavy snow, or rain and snow mixed or hail",
  95: "Thunderstorm, slight or moderate, without hail",
  96: "Thunderstorm, slight or moderate, with hail",
  97: "Thunderstorm, heavy, without hail",
  98: "Thunderstorm combined with duststorm or sandstorm at time of observation",
  99: "Thunderstorm, heavy, with hail",
};
